# Use a Python image
FROM python:3.9

# Set working directory
WORKDIR /worker_services

# Install dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Copy all files in worker_services into the image
COPY . .
RUN chmod +x /worker_services/start_workers.sh  # Make the script executable

# Start workers
CMD ["sh", "/worker_services/start_workers.sh"]
